# This is a basic workflow to help you get started with Actions

name: Test Integrity Of Build
# Controls when the workflow will run
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - name: ENV
        with: # Set the secret as an input
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
        env: # Or as an environment variable
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --mode skip-build

      - name: Lint All Projects
        run: yarn nx run-many --target=lint 

      - name: Build All Projects
        run: yarn nx run-many --target=build 

      - name: Pack All Server
        run: yarn nx run-many --target=pack 
