# This is a basic workflow to help you get started with Actions

name: Feature Building Test
# Controls when the workflow will run
on:
  push:
    branches:
      - 'feat/**'
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
        with:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
        env: # Or as an environment variable
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

      - run: git fetch --no-tags --prune --depth=1 origin main

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --mode skip-build

      - name: Yarn Affected Lint
        run: yarn nx affected --target=lint --base=origin/main

      - name: Yarn Affected Build
        run: yarn nx affected --target=build --base=origin/main

      - name: Yarn Affected Pack Server
        run: yarn nx affected --target=pack --base=origin/main
